### ISSUE TITLE
Manage different sampling rate files

### ISSUE THREAD

**Issue by turpaultn** [justinsalamon/scaper#71] opened 2020-02-11 17:40 UTC
I realized that when I generate files from different sampling rate audio files, it keeps the default 44,1kHz, is it expected behavior ?
I have 16kHz files for background and 44.1kHz files for foreground, I thought it would generate files with the lowest sample rate.
I am now using `sc.sr = 16000`.
If it is expected behavior, sorry and just close the issue please.

**Comment by justinsalamon** [comment] 2020-02-15 02:58
@turpaultn the intended behavior is that the sample rate of the output soundscape audio file is whatever you set `sc.sr` to be. By default it's set to 44100. If you change `sc.sr` to some other value (e.g. 16000), the output should have that sampling rate. 

Is this not the behavior you are observing?

I don't think there's a good justification for downsampling everything to the lowest sample rate of any file, since that could result in very poor quality for scenarios where most of your data has a high sample rate but just a few files have a small rate. If anything, it would make sense to default to the highest sample rate. But even that doesn't make sense to me, because it's not very predictable. I prefer the current design where you choose a sample rate and everything gets resampled to this sample rate, so you know exactly what you're getting regardless of your input data.

**Comment by turpaultn** [comment] 2020-02-17 08:49
I realized after some time that indeed, it makes more sense to do it like that.

To avoid people having the same problem I had, what do you think about a warning when we generate file from different sampling rate ?

**Comment by justinsalamon** [comment] 2020-02-17 20:48
Raising a warning is an option, though I'm a little concerned it will result in a very large number of warnings when working with a heterogenous set of foreground sounds with different sampling rates.

I think the main issue right now is that the sampling rate parameter is "hidden" because it's not set in the constructor of the Scaper object and is generally not very well documented. I think the best way to address this is via #60, i.e. moving `sr` (as well as a few more parameters) into the constructor of the Scaper object with a proper docstring. This way, it will be visible and clearly stated that all events will be resampled to the provided `sr`, so hopefully will avoid confusion around this moving forward.

Closing this issue out in favor of #60.

**Closed by justinsalamon** 2020-02-17 20:48 UTC

**Comment by pseeth** [comment] 2020-02-29 00:26
Quick comment on this issue: highly recommend you resample all your data before feeding it to Scaper at all. Generation can get really slow if you expect Scaper to resample every file every time it creates a soundscape (note that it needs to resample even if it resampled that file before for a different soundscape).

**Comment by turpaultn** [comment] 2020-02-29 02:06
Thank you for the recommendation. I'll try to find a way to do that then.
